name: UnioFactions
main: me.uniodex.uniofactions.UnioFactions
author: 'UnioDex'
version: 2.0

depend: [Factions, WorldGuard, Vault]
softdepend: [Citizens, MythicMobs, CombatLogX, PlaceholderAPI, Jobs, UnioCustomItems]

commands:
  tpchunk:
    description: tpchunk
  uniofactions:
    description: uniofactions
  chatcolor:
    description: chatcolor
    aliases: [renk]
  commands:
    description: commands
    aliases: [komutlar]
  quests:
    description: quests
    aliases: [görevler, gorevler]
  meslek: #jobs
    description: meslek
    aliases: [meslekler]